// Last Update: 2025-04-01

module.exports = {
  productionInstitutions: [
    { clave_institucion: 40995, nombreCorto: "Banco Wgo Push" }, // Added by user
    { clave_institucion: 40993, nombreCorto: "Banco Wgo Qr" }, // Added by user
    { clave_institucion: 37019, nombreCorto: "BANJERCITO" },
    { clave_institucion: 37166, nombreCorto: "BaBien" },
    { clave_institucion: 40002, nombreCorto: "BANAMEX" },
    { clave_institucion: 40012, nombreCorto: "BBVA MEXICO" },
    { clave_institucion: 40014, nombreCorto: "SANTANDER" },
    { clave_institucion: 40021, nombreCorto: "HSBC" },
    { clave_institucion: 40030, nombreCorto: "BAJIO" },
    { clave_institucion: 40036, nombreCorto: "INBURSA" },
    { clave_institucion: 40042, nombreCorto: "MIFEL" },
    { clave_institucion: 40044, nombreCorto: "SCOTIABANK" },
    { clave_institucion: 40058, nombreCorto: "BANREGIO" },
    { clave_institucion: 40059, nombreCorto: "INVEX" },
    { clave_institucion: 40060, nombreCorto: "BANSI" },
    { clave_institucion: 40062, nombreCorto: "AFIRME" },
    { clave_institucion: 40072, nombreCorto: "BANORTE" },
    { clave_institucion: 40102, nombreCorto: "ACCENDO BANCO" },
    { clave_institucion: 40112, nombreCorto: "BMONEX" },
    { clave_institucion: 40113, nombreCorto: "VE POR MAS" },
    { clave_institucion: 40127, nombreCorto: "AZTECA" },
    { clave_institucion: 40130, nombreCorto: "COMPARTAMOS" },
    { clave_institucion: 40132, nombreCorto: "MULTIVA BANCO" },
    { clave_institucion: 40133, nombreCorto: "ACTINVER" },
    { clave_institucion: 40136, nombreCorto: "INTERCAM BANCO" },
    { clave_institucion: 40137, nombreCorto: "BANCOPPEL" },
    { clave_institucion: 40138, nombreCorto: "ABC CAPITAL" },
    { clave_institucion: 40140, nombreCorto: "CONSUBANCO" },
    { clave_institucion: 40143, nombreCorto: "CIBANCO" },
    { clave_institucion: 40145, nombreCorto: "BBASE" },
    { clave_institucion: 40147, nombreCorto: "BANKAOOL" },
    { clave_institucion: 40148, nombreCorto: "PAGATODO" },
    { clave_institucion: 40150, nombreCorto: "INMOBILIARIO" },
    { clave_institucion: 40151, nombreCorto: "DONDE" },
    { clave_institucion: 40152, nombreCorto: "BANCREA" },
    { clave_institucion: 40156, nombreCorto: "SABADELL" },
    { clave_institucion: 90634, nombreCorto: "FINCOMUN" },
    { clave_institucion: 90646, nombreCorto: "STP" },
    { clave_institucion: 90659, nombreCorto: "ASP INTEGRA OPC" },
    { clave_institucion: 90684, nombreCorto: "TRANSFER" },
  ],
  betaInstitutions: [
    { clave_institucion: 301, nombreCorto: "MEMBER_A" },
    { clave_institucion: 302, nombreCorto: "GEM-BANAMEX2" },
    { clave_institucion: 314, nombreCorto: "GEM-SANTANDES" },
    { clave_institucion: 322, nombreCorto: "GEM-HSBC_DES" },
    { clave_institucion: 414, nombreCorto: "GEM-SANTANDE" },
    { clave_institucion: 421, nombreCorto: "GEM-HSBC2" },
    { clave_institucion: 447, nombreCorto: "GEM-BANKAOOL" },
    { clave_institucion: 448, nombreCorto: "GEM-PAGATODO" },
    { clave_institucion: 450, nombreCorto: "GEM-INMOBIMEX" },
    { clave_institucion: 451, nombreCorto: "GEM-DONDE" },
    { clave_institucion: 452, nombreCorto: "GEM-BM BANCREA" },
    { clave_institucion: 502, nombreCorto: "GEM-BANAMEX" },
    { clave_institucion: 512, nombreCorto: "GEM-BANCOMER" },
    { clave_institucion: 519, nombreCorto: "GEM-BANJERCITO" },
    { clave_institucion: 530, nombreCorto: "GEM-BAJIO" },
    { clave_institucion: 536, nombreCorto: "GEM-INBURSA" },
    { clave_institucion: 542, nombreCorto: "GEM-MIFEL" },
    { clave_institucion: 558, nombreCorto: "GEM-BANREGIO" },
    { clave_institucion: 559, nombreCorto: "GEM-INVEX" },
    { clave_institucion: 560, nombreCorto: "GEM-BANSI" },
    { clave_institucion: 562, nombreCorto: "GEM-AFIRME" },
    { clave_institucion: 566, nombreCorto: "GEM-BANSEFI" },
    { clave_institucion: 572, nombreCorto: "GEM-BANORTE/IXE" },
    { clave_institucion: 612, nombreCorto: "GEM-MONEX" },
    { clave_institucion: 613, nombreCorto: "GEM-VE POR MAS" },
    { clave_institucion: 627, nombreCorto: "GEM-AZTECA" },
    { clave_institucion: 628, nombreCorto: "GEM-AUTOFIN" },
    { clave_institucion: 630, nombreCorto: "GEM-COMPARTAMOS" },
    { clave_institucion: 631, nombreCorto: "GEM-FAMSA" },
    { clave_institucion: 632, nombreCorto: "GEM-MULTIVA" },
    { clave_institucion: 633, nombreCorto: "GEM-BCO ACTINVER" },
    { clave_institucion: 636, nombreCorto: "GEM-INTERCAM" },
    { clave_institucion: 637, nombreCorto: "GEM-BANCOPPEL" },
    { clave_institucion: 640, nombreCorto: "GEM-CONSUBANCO" },
    { clave_institucion: 654, nombreCorto: "GEM-FINTERRA" },
    { clave_institucion: 656, nombreCorto: "GEM-SABADELL" },
    { clave_institucion: 743, nombreCorto: "GEM-CONSULTORIA" },
    { clave_institucion: 756, nombreCorto: "GEM-BANCOPP3" },
    { clave_institucion: 757, nombreCorto: "GEM-BANCOPP2" },
    { clave_institucion: 834, nombreCorto: "GEM-FINCOMUN" },
    { clave_institucion: 846, nombreCorto: "GEM-STP" },
    { clave_institucion: 853, nombreCorto: "GEMELO KUSPIT" },
    { clave_institucion: 854, nombreCorto: "GEM-BBASE" },
    { clave_institucion: 860, nombreCorto: "GEM-ASP-FINANC" },
    { clave_institucion: 881, nombreCorto: "GEM-PRESTAMO" },
  ],
};
